server:
  port: 8080

spring:
  application:
    name: minicloud-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: public-auth
          uri: lb://MINICLOUD-IAM
          predicates:
            - Path=/api/v1/auth/**
          # Auth endpoints are public

        - id: iam-management
          uri: lb://MINICLOUD-IAM
          predicates:
            - Path=/api/v1/iam/**
          filters:
            - AuthenticationFilter

        - id: core-backend-v1
          uri: lb://MINICLOUD-BACKEND
          predicates:
            - Path=/api/v1/**
          filters:
            - AuthenticationFilter
            - RewritePath=/api/v1/(?<segment>.*), /api/$\{segment}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
